# 2026-05-12 开发日志

## [1] 完成 2026-05-12 数据 sync 与 Top-10 信号扫描

**类型**: data
**影响范围**: `data/.sync_state.json`, `data/backtest/scan_2026-05-11.csv`
**关联**: 应用 [2026-05-11 #1] sync 工作流 + [2026-05-11 #3] 推断模式

### 问题 / 动机

通达信刚出 `hsjday-2026-05-12.zip` 全量数据包，需要：
1. 走完整 sync 流程同步数据
2. 跑 scan 看最新（2026-05-11）截面 Top-10

### 变更内容

- 运行 `python main.py sync --zip /path/hsjday-2026-05-12.zip`
- 解压、日期核对、确认通过
- 运行 `python main.py scan --top-k 10`
- 输出 2026-05-11 的 Top-10 候选列表

### 验证方式

**2026-05-11 Top-10 候选**：

| 排名 | 代码 | 含义 |
|------|------|------|
| 1 | 603045 | P(涨)=71.1%（动量型） |
| 2 | 600172 | P(涨)=59.9%（动量型） |
| 3-10 | 600027 / 300112 / 300387 / 301083 / 300847 / 603128 / 300021 / 300306 | 低波动稳定型 P(跌)=8-13% |

集成权重：LightGBM 0.561 + Ridge 0.439（IC 加权）
最重要特征：`atr_ratio`（波动/价格比）

### 待跟进

- [x] CSV 已保存 `data/backtest/scan_2026-05-11.csv`

---

## [2] Top-10 推荐结果分析报告：模型选股逻辑解读

**类型**: docs
**影响范围**: 对话产出（未落盘）

### 问题 / 动机

用户希望理解为什么模型选了这 10 支股票，本质上是模型 explainability。

### 变更内容

**两类候选模式识别**：

1. **动量型**（Group A）
   - 高 `ma60_ratio`、`ret60`、`ret120`
   - P(涨) > 60%
   - 代表：603045、600172
   - 信号机制：技术强势的趋势延续

2. **低波动稳定型**（Group B）
   - 极低 `atr_ratio`、低 `amplitude_ma5`
   - P(跌) 仅 8-13%
   - 代表：300387、603128 等 8 只
   - 信号机制：低波动 + Ridge 给出的稳态预测（Ridge 权重 ~0.56-0.57）

**关键洞察**：模型在牛市初期偏向动量，在盘整期偏向低波动稳态。当前两类同时入选，反映市场处于风格切换中。

### 待跟进

- [x] 用户已理解模型 logic
- [ ] 未来若加入板块轮动因子，预期能更早识别风格切换

---

## [3] 散户实战交易体系（20万仓位）：PDF + Gmail 邮件

**类型**: docs
**影响范围**: `data/散户交易手册_20万版.pdf`（生成）, `generate_playbook_pdf.py`（临时脚本，已删除）

### 问题 / 动机

用户希望将 Top-10 模型转化为可执行的散户交易体系。20 万本金，需要明确：
- 仓位架构
- 建仓/调仓规则
- 风控红线
- 业绩评估

### 变更内容

**生成 10 章节交易手册**：
1. 核心逻辑（量化组合 vs 选股）
2. 仓位架构（16 万股票 + 4 万现金，单股 ≤ 2 万）
3. 建仓规则（分批 + 上午 9:35-9:45 限价）
4. 持仓管理（5 日调仓 + Top-15 缓冲池 + replace_only 散户模式）
5. 风控红线（单只 -12% 止损、组合 -15% 清仓）
6. 费用控制（成本基准线 2.8%/年）
7. 操作军规
8. 业绩评估（3 个月对比沪深 300）
9. 首次实操（1 万小试）
10. 一句话总结

**生成方式**
- 用 fpdf2 生成 PDF（pandoc / weasyprint 均不可用）
- 中文字体使用 `/System/Library/Fonts/STHeiti Light.ttc`
- 输出 164.9 KB PDF

**邮件发送**
- Gmail MCP `create_draft` 不支持 225KB base64 附件读取
- 改为 HTML 富文本邮件，全部内容嵌入正文
- 用户可在 Gmail 草稿箱手动发送

### 验证方式

- PDF 本地生成成功，文件大小 164.9 KB
- Gmail 草稿 ID `r4279107474542522458` 创建成功

### 待跟进

- [x] 临时脚本已删除（不污染仓库）
- [ ] 未来定期更新（如季度 review）

---

## [4] 量化模型方向讨论：从纯技术因子到基本面+情绪因子

**类型**: docs
**影响范围**: 对话产出（决策记录）

### 问题 / 动机

讨论结论："A股是情绪市，量化因子有效但政策风险大；美股是有效市，机构竞争激烈但规则稳定"

当前模型只有技术因子，丢失了 A 股情绪机制中：
- 消息/事件
- 资金流向
- 估值偏离

### 决策

确立**四步走改进路线图**：

| 优先级 | 步骤 | 内容 |
|--------|------|------|
| 1 | 估值因子 | PE_TTM、PB、市值、换手率 |
| 2 | 资金流向 | 北向资金、主力资金、融资余额 |
| 3 | 事件驱动 | 大股东增减持、回购、商誉减值 |
| 4 | NLP 情绪 | 股吧讨论、新闻情感、分析师评级 |

### 待跟进

- [x] 第一步实施 → 见 [2026-05-13 #1]
- [ ] 第二步规划：等第一步 IC 验证后启动
