# 2026-05-14 开发日志

## [1] Phase1 重跑 + Phase2 新模型训练（基本面因子验证）

**类型**: data / feat
**影响范围**: `data/processed/market_features.parquet`, `data/models/`
**关联**: [2026-05-13 #1] 基本面因子实现

### 问题 / 动机

基本面因子代码已于 2026-05-13 实现，fetch-fund 全量拉取完成后，需重跑 phase1（特征工程）和 phase2（模型训练）验证因子有效性。

### 变更内容

**Phase1 结果**：

| 指标 | 结果 |
|------|------|
| 有效股票 | 5526 只（跳过243/基本面缺失427） |
| 数据集 | 6,451,004 行 × 91 列（含56个因子） |
| 文件大小 | 3.3 GB（vs 旧版 2.3 GB） |
| 时间范围 | 2021-01-05 ~ 2026-04-29 |
| 耗时 | 27 分钟 |

**Phase2 评估结果（基本面 vs 基线对比）**：

| 集合 | 基线 IC | 新 IC | 提升 |
|------|--------|-------|------|
| 训练集 | 0.1135 | 0.1350 | +19% |
| 验证集 | 0.0606 | 0.0650 | +7.3% |
| 测试集 | 0.0211 | 0.0236 | +11.8% |

**基本面因子特征重要性（Top30 中 6 个）**：

| 排名 | 因子 | 说明 |
|------|------|------|
| #4 | `market_cap_log` | 市值规模，最强基本面信号 |
| #6 | `pb_self_pct` | PB 自身历史分位 |
| #8 | `float_mc_log` | 流通市值 |
| #13 | `pb_log` | PB 估值 |
| #19 | `peg_value` | PEG |
| #24 | `pe_ttm_log` | PE(TTM) |

市值类因子（规模效应）是最有效的基本面信号。

### 验证方式

- phase1 完整输出与日志核对
- phase2 切分与历史完全一致（训练4,415,306行 / 验证1,031,240 / 测试1,004,458）
- 特征重要性图保存于 `data/models/feature_importance.png`

### 待跟进

- [x] 基本面因子有效，进入下一步

---

## [2] Walk-Forward CV 诊断（过拟合分析）

**类型**: feat / analysis
**影响范围**: `src/models/trainer.py`（新增 `walk_forward_cv()`、`run_training_rolling()`）, `main.py`（`--walk-forward` 参数）
**关联**: 测试集 IC 衰减问题诊断

### 问题 / 动机

测试集 IC 仅 0.0236，远低于验证集 0.0650。需要判断：
- 是模型过拟合（根本问题），还是
- 市场 regime 变化（政策驱动行情导致截面信号失效）

### 变更内容

**新增 `walk_forward_cv(df, min_train_months=18, pred_months=6)`**：
- 扩展窗口，18个月起步，每折 OOS 6个月
- 内部验证集：训练集最后 15%（供 LightGBM 早停）
- 逐日 Pearson IC 计算
- 结果保存至 `data/models/walk_forward_results.json`

**新增 `--walk-forward` 参数**：`python main.py 2 --walk-forward`

### 8 折 OOS IC 结果

| 折叠 | OOS 区间 | OOS IC | 市场特征 |
|------|---------|--------|---------|
| 1 | 2022H2~2023H1 | 0.0977 | 熊转牛 |
| 2 | 2023H1~2023H2 | 0.0853 | 震荡筑底 |
| 3 | 2023H2~2024H1 | 0.0689 | 持续弱势 |
| 4 | 2024H1~2024H2 | **0.1302** | 2月低点反弹 |
| 5 | 2024H2~2025H1 | 0.0558 | 9·24 政策冲击 |
| 6 | 2025H1~2025H2 | **0.0946** | 政策退潮后恢复 |
| 7 | 2025H2~2026Q1 | 0.0462 | 训练数据滞后期 |
| 8 | 2026Q1~2026Q2 | -0.0185 | ⚠️ 仅37天+关税冲击 |
| **整体** | | **0.0700** | vs 固定切分测试集 0.0236 |

### 关键诊断结论

1. **模型本身健康**：整体 OOS IC = 0.0700（远高于固定切分测试集 0.0236）
2. **IC 低谷 = 政策冲击**：Fold 5（9·24大反弹）、Fold 8（关税冲击）均为无差别行情，截面选股信号必然失效
3. **非过拟合**：正常分化行情下 IC 稳定在 0.07-0.13
4. **训练数据滞后**：Fold 7（训练至2025-09）预测2025H2-2026的 IC 达0.0462，是固定切分测试 IC 的2倍，说明更新训练数据能显著改善实盘信号

### 还原实验（滚动窗口）

尝试 `run_training_rolling(train_years=2)`（最近2年数据）：
- 验证集 IC：0.0560（低于固定切分 0.0650）
- 测试集 IC：0.0123（低于固定切分 0.0236）
- 结论：训练截止日相同（2024-09），去掉2021-2022旧数据反而丢失了有益的模式多样性，已放弃

**操作**：已恢复固定切分生产模型。

### 待跟进

- [x] 诊断完成，结论清晰
- [ ] 每次 sync 新数据后立即重跑 phase2，让训练窗口向前推进（最根本的改善方式）

---

## [3] --final 模式：全量数据生产模型

**类型**: feat
**影响范围**: `src/models/trainer.py`（新增 `run_training_final()`、`train_lgbm_fixed()`）, `main.py`（`--final` 参数）

### 问题 / 动机

70/15/15 切分后，验证集（2024-09 ~ 2025-07）有标签但不参与训练，相当于"浪费"了 103 万行数据。生产模型应在评估后用全量有标签数据重训，充分利用每一天的数据。

### 变更内容

**新增 `run_training_final(df, best_iteration, w_lgbm, w_ridge, feature_cols)`**：
- 评估阶段不变（70/15/15 切分，IC 指标诚实）
- 评估后：用全量 6,451,004 行 + 固定 639 轮（来自评估阶段 best_iteration）重训
- 无早停（固定轮数防止在全量数据上过度拟合）
- 集成权重复用评估阶段结果（IC 比例稳定）
- 覆盖写入 `data/models/` 生产模型文件

**新增 `train_lgbm_fixed(X, y, feature_names, num_rounds)`**：无验证集的固定轮数训练

**LightGBM 参数提取为模块级常量 `_LGBM_PARAMS`**（消除 `train_lgbm` 与 `train_lgbm_fixed` 的代码重复）

**用法**：`python main.py 2 --final`（可与 `--walk-forward` 独立使用）

### 验证方式

- 评估 IC 与固定切分完全一致（0.1350 / 0.0650 / 0.0236）
- Final 模型：6,451,004 行，639 轮，LGB=0.538 / Ridge=0.462
- Scan 输出正常（2026-05-11 截面，5097只，Top-10 完整）

### 2026-05-11 最新 Top-10（Final 全量模型）

| 排名 | 代码 | 板块 | 收盘价 | 信号值 |
|------|------|------|--------|--------|
| 1 | 603045 | 沪市主板 | 68.35 | 3.099 |
| 2 | 300112 | 创业板 | 8.60 | 1.947 |
| 3 | 300105 | 创业板 | 6.93 | 1.920 |
| 4 | 000900 | 深市主板 | 4.21 | 1.907 |
| 5 | 600697 | 沪市主板 | 12.73 | 1.833 |
| 6 | 301355 | 创业板 | 13.13 | 1.810 |
| 7 | 300958 | 创业板 | 14.70 | 1.789 |
| 8 | 603137 | 沪市主板 | 14.14 | 1.774 |
| 9 | 300305 | 创业板 | 6.80 | 1.761 |
| 10 | 301320 | 创业板 | 18.04 | 1.736 |

### 待跟进

- [ ] **每次 sync 后执行完整流程**：`sync → phase1 → python main.py 2 --final → scan`
- [ ] **资金流向因子**（基本面第二步）：北向资金、主力资金净流入、融资余额
